version: "3"

services:
  btcpayserver:
    restart: unless-stopped
    container_name: generated_btcpayserver_1
    image: ${BTCPAY_IMAGE:-btcpayserver/btcpayserver:1.13.5$<BTCPAY_BUILD_CONFIGURATION>?}
    expose:
      - "49392"
    environment:
      # BTCPay settings
      BTCPAY_POSTGRES: User ID=${PSQL_UID:-foo};Host=${PSQL_HOST:-postgres};Port=5432;Database=${PSQL_DBNAME:-btcpay0};Password=${PSQL_PSW:-foobarbaz}
      BTCPAY_EXPLORERPOSTGRES: User ID=${PSQL_UID:-foo};Host=${PSQL_HOST:-postgres};Port=5432;Application Name=btcpayserver;MaxPoolSize=80;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHCONNECTION: "root@host.docker.internal"
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_SSHAUTHORIZEDKEYS: ${BTCPAY_SSHAUTHORIZEDKEYS}
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_UPDATEURL: https://api.github.com/repos/btcpayserver/btcpayserver/releases/latest
      BTCPAY_DOCKERDEPLOYMENT: "true"
    volumes:
      - "btcpay_datadir:/datadir"
      - "nbxplorer_datadir:/root/.nbxplorer"
      - "$<BTCPAY_HOST_SSHAUTHORIZEDKEYS>?:${BTCPAY_SSHAUTHORIZEDKEYS}"
      - "btcpay_pluginsdir:/root/.btcpayserver/Plugins"

volumes:
  btcpay_datadir:
  btcpay_pluginsdir:

required:
  - "nbxplorer"
  - "btcpayserver"
recommended:
  - "opt-add-tor"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.0.0/16