version: "3"

services:

  nbxplorer:
    restart: unless-stopped
    container_name: generated_nbxplorer_1
    image: nicolasdorier/nbxplorer:2.5.2
    expose:
      - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_POSTGRES: User ID=${PSQL_UID:-foo};Host=${PSQL_HOST:-postgres};Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=${PSQL_DBNAME:-btcpay0}nbxplorer;Password=${PSQL_PSW:-foobarbaz}
      NBXPLORER_AUTOMIGRATE: 1
      NBXPLORER_NOMIGRATEEVTS: 1
      NBXPLORER_DELETEAFTERMIGRATION: 1
    volumes:
      - "nbxplorer_datadir:/datadir"

volumes:
  nbxplorer_datadir:
