version: "3"

services:
  btctransmuter:
    restart: unless-stopped
    image: btcpayserver/btctransmuter:0.0.59
    container_name: btctransmuter
    environment:
      TRANSMUTER_Database: User ID=${PSQL_UID:-foo};Host=${PSQL_HOST:-postgres};Port=5432;Database=${PSQL_DBNAME:-btcpay0}transmuter;Password=${PSQL_PSW:-foobarbaz}
      TRANSMUTER_DatabaseType: postgres
      TRANSMUTER_DataProtectionDir: data/keys
      TRANSMUTER_DataProtectionApplicationName: btctransmuter
      TRANSMUTER_ROOTPATH: "/btctransmuter"
      TRANSMUTER_ExtensionsDir: data/extensions
      NBXplorer_Cryptos: ${BTCPAY_CRYPTOS}
      NBXplorer_Uri: http://nbxplorer:32838/
      NBXplorer_NetworkType: ${NBITCOIN_NETWORK:-regtest}
      NBXplorer_UseDefaultCookie: 1
      LETSENCRYPT_HOST: ${BTCTRANSMUTER_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
      VIRTUAL_HOST: ${BTCTRANSMUTER_HOST}
      VIRTUAL_HOST_NAME: "btctransmuter"
      TRANSMUTER_BTCPayAuthServer: "http://btcpayserver:49392"
    labels:
      traefik.enable: "true"
      traefik.http.routers.btctransmuter.rule: Host(`${BTCPAY_HOST}`) && (Path(`/btctransmuter`) || PathPrefix(`/btctransmuter/`))
    expose:
      - "80"
    links:
      - nbxplorer
      - btcpayserver
    volumes:
      - "btctransmuter_datadir:/app/data"
      - "nbxplorer_datadir:/root/.nbxplorer"
  btcpayserver:
    environment:
      BTCPAY_EXTERNALSERVICES: "BTC Transmuter:btctransmuter;"
volumes:
  btctransmuter_datadir:
